# configuration for code coverage testing with codecov
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
codecov: 
 token: ${{ secrets.CODECOV_TOKEN }}