
#ifndef SVZERODSOLVER_MODEL_BLOCK_TYPE_HPP_
#define SVZERODSOLVER_MODEL_BLOCK_TYPE_HPP_

namespace zd_model {

enum class BlockType {
  BLOODVESSEL = 0,
  JUNCTION = 1,
  BLOODVESSELJUNCTION = 2,
  RESISTIVEJUNCTION = 3,
  FLOWBC = 4,
  PRESSUREBC = 5,
  RESISTANCEBC = 6,
  WINDKESSELBC = 7,
  OPENLOOPCORONARYBC = 8,
  CLOSEDLOOPCORONARYLEFTBC = 9,
  CLOSEDLOOPCORONARYRIGHTBC = 10,
  CLOSEDLOOPRCRBC = 11,
  CLOSEDLOOPHEARTPULMONARY = 12
};

};

#endif

