
name: Build
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libeigen3-dev libsimdjson-dev libjsoncpp-dev build-essential cmake
      - name: Build svZeroDSolver
        run: |
          mkdir Debug
          cd Debug
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
  macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install eigen jsoncpp simdjson
      - name: Build svZeroDSolver
        run: |
          mkdir Debug
          cd Debug
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
    
      