
name: Build and test
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential cmake libeigen3-dev libsimdjson-dev libjsoncpp-dev
          sudo apt-get update
          sudo apt-get install python-pybind11
      - name: Build svZeroDSolver
        run: |
          mkdir Release
          cd Release
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
      - name: Install test dependencies
        run: |
          conda create -n zerod python=3.9
          conda run -n zerod pip install pytest pytest-cov pytest-mock
          conda run -n zerod pip install -e .
      - name: Test the build
        run: |
          conda run -n zerod pytest tests/test_integration_cpp.py
  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install eigen jsoncpp simdjson pybind11
      - name: Build svZeroDSolver
        run: |
          mkdir Release
          cd Release
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
      - name: Install test dependencies
        run: |
          conda create -n zerod python=3.9
          conda run -n zerod pip install pytest pytest-cov pytest-mock
          conda run -n zerod pip install -e .
      - name: Test the build
        run: |
          conda run -n zerod pytest tests/test_integration_cpp.py
    
      