name: Test Visualization Application

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Install Graphviz
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Install Graphviz (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install graphviz

      - name: Run tests
        run: |
          pytest tests/test_dirgraph.py
